

CREATE DATABASE shoppingmall default CHARACTER SET UTF8;

CREATE TABLE member
(CREATE DATABASE shoppingmall default CHARACTER SET UTF8;

 CREATE TABLE member
 (
      _id INT PRIMARY KEY AUTO_INCREMENT,
      userId VARCHAR(50) NOT NULL,
      name VARCHAR(32) NOT NULL,
      pw VARCHAR(12) NOT NULL,
      email VARCHAR(100) NOT NULL,
      contact VARCHAR(15) NOT NULL
 ) ENGINE=INNODB;
 DESCRIBE member;

 SELECT * FROM member;
     _id INT PRIMARY KEY AUTO_INCREMENT,
     userId VARCHAR(50) NOT NULL,
     name VARCHAR(32) NOT NULL,
     pw VARCHAR(12) NOT NULL,
     email VARCHAR(100) NOT NULL,
     contact VARCHAR(15) NOT NULL
) ENGINE=INNODB;
DESCRIBE member;

SELECT * FROM member;